### ISSUE TITLE
Firefox съел границу у столбца студентов

### ISSUE THREAD

**Issue by kasmacioma** [xapdkop/fixarm#16]
"Липкие студенты" влияет только на границу заголовка столбца
![изображение](https://user-images.githubusercontent.com/30960705/140586564-fd28034e-8c71-4837-a0d3-937351c1bbf9.png)

**Comment by xapdkop** [comment]
Фикс добавлен в dev

**Comment by kasmacioma** [comment]
Исправлено в d8817456d295e68abebfe7db183b956524027970
